

server:
  port: 8090
  tomcat:
    use-relative-redirects: true  # Spring Boot 에서 페이지 리다이렉트 시 https에서 http로 리다이텍트 되어 페이지 오류가 가는 부분 수정
  servlet:
    encoding:
      force-response: true

spring:
#  thymeleaf:
#    prefix: classpath:/templates/thymeleaf/
#    check-template: true
#    suffix: .mustache
#    mode: HTML
#    cache: false # default true, 개발 시에는 false로 두는 것이 좋음.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://juniza82.synology.me:33077/myhome?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: admin
    password: Rlawhdgus1@
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
        ejb:
          use_class_enhancer: true
    datasource:
      initialization-mode: never





